### ISSUE TITLE
HttpRequestException when creating Client

### ISSUE THREAD

**Issue by stijnvha** [craysiii/Ninja-Api#14]
Hi, when creating the Client as follows:

```
var client = new Client(
    clientId: clientId,
    clientSecret: clientSecret,
    scopes: ApplicationScopes.MONITORING,
    instance: Instance.EU
);
```

I get the following exception:
```
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|53_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RestSharp.ResponseThrowExtension.ThrowIfError[TokenResponse](RestResponse`1 response)
   at RestSharp.RestClientExtensions.<PostAsync>d__15`1[[NinjaOne_Api.Library.Authentication.TokenResponse, NinjaOne-Api.Library, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at NinjaOne_Api.Library.Authentication.NinjaAuthenticator.GetToken()
   at NinjaOne_Api.Library.Authentication.NinjaAuthenticator.GetAuthenticationParameter(String accessToken)
   at RestSharp.Authenticators.AuthenticatorBase.Authenticate(IRestClient client, RestRequest request)
   at RestSharp.RestClient.ExecuteRequestAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at NinjaOne_Api.Library.Client.Get(RestRequest request)
   at NinjaOne_Api.Library.Client.<GetResources>d__7`1[[NinjaOne_Api.Library.Types.OrganizationBase, NinjaOne-Api.Library, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at NinjaOne_Api.Library.Client.GetOrganizations(Int32 after, Int32 pageSize)
```

My (Blazor) application is written in .NET8

Could you look into this?

**Comment by craysiii** [comment]
Good Day - It looks like there is a potential authentication issue which is causing it to throw - though without the returned json, it's hard to tell for sure.

I should have some time this weekend to implement proper logging and better handle errors returned by the API.

**Comment by stijnvha** [comment]
That would be awesome! I have verified the credentials to be correct.
Awesome work!

**Comment by stijnvha** [comment]
When using these credentials in Postman I am getting redirected to the NinjaRMM page to authorize the API changes. Maybe that is keeping the tokens from working? If so, is it possible to implement a system that opens a window to authorize and uses a redirect Uri to obtain the token?

![image](https://github.com/craysiii/Ninja-Api/assets/62998441/c6f2ed9b-d389-45e2-8f49-859b1a4acfa2)

**Comment by craysiii** [comment]
I think I see what might be the issue here.

When you created the API Key, which Grant Type did you choose?

Currently only "Client Credentials" is supported. The auth flow that you show now should be the "Authorization Code" grant type. I plan to support it in the future but am not there yet.

Please try creating an API key like so:
![image](https://github.com/craysiii/Ninja-Api/assets/1387727/5f029851-9a6c-4430-94c2-6bc958ad19c3)

Let me know if that doesn't work.

**Comment by stijnvha** [comment]
Thanks! I have tried to create key using the exact method as you showed above but still can't receive a token (same exception)

**Comment by craysiii** [comment]
Understood, will investigate more, thank you for the report!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stijnvha** [comment]
Hey, did you manage to investigate this issue?

**Comment by craysiii** [comment]
Hey there @stijnvha , apologies for taking so long on this. Work has been hectic for the past few months and I haven't had time to work on personal projects.

I've made some major changes to how the library works, added logging, and also upgraded the .Net version to 8.0. If you're still intent on using the library, could you try the new 0.2.0 release and see if you have better luck?

**Comment by stijnvha** [comment]
I will try it later this week (if not next week)
Thanks so much!

**Comment by stijnvha** [comment]
Everything is working greatly!
For other people seeing this issue. Please make sure to *not* use webassembly as those [can't make network calls](https://github.com/restsharp/RestSharp/issues/1524#issuecomment-719330051)
